# Generated by Django 4.2.28 on 2026-02-23 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catechism', '0018_increase_topic_name_max_length'),
        ('accounts', '0002_highlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='InlineComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type_tag', models.CharField(choices=[('question', 'Question Text'), ('answer', 'Answer Text'), ('commentary', 'Commentary')], max_length=20)),
                ('selected_text', models.TextField()),
                ('occurrence_index', models.PositiveIntegerField(default=0)),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commentary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inline_comments', to='catechism.commentary')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inline_comments', to='catechism.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inline_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
