# Generated by Django 4.2.28 on 2026-03-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inlinecomment",
            name="content_type_tag",
            field=models.CharField(
                choices=[
                    ("question", "Question Text"),
                    ("answer", "Answer Text"),
                    ("commentary", "Commentary"),
                    ("scripture", "Scripture Proofs"),
                ],
                max_length=20,
            ),
        ),
    ]
