# Generated by Django 4.2.30 on 2026-08-23 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("catechism", "0022_add_reformed_confessions_tradition"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0007_delete_supportersubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemorizationCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repetitions", models.PositiveIntegerField(default=0)),
                ("interval_days", models.PositiveIntegerField(default=0)),
                ("ease", models.FloatField(default=2.5)),
                (
                    "due_on",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                ("lapses", models.PositiveIntegerField(default=0)),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memorization_cards",
                        to="catechism.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memorization_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "due_on",
                    "question__catechism__abbreviation",
                    "question__number",
                ],
                "unique_together": {("user", "question")},
            },
        ),
    ]
