# Generated by Django 4.2.30 on 2026-08-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_memorization_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_review_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="longest_streak",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="review_streak",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_reviews",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
