# Generated by Django 4.2.28 on 2026-02-20 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentarySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(unique=True)),
                ('question_start', models.PositiveIntegerField()),
                ('question_end', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(db_index=True, unique=True)),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('proof_texts', models.TextField(blank=True, help_text='Semicolon-separated Scripture references')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='catechism.topic')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaries', to='catechism.question')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='catechism.commentarysource')),
            ],
            options={
                'verbose_name_plural': 'commentaries',
                'ordering': ['source__slug'],
                'unique_together': {('question', 'source')},
            },
        ),
        migrations.CreateModel(
            name='FisherSubQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('commentary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='catechism.commentary')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('commentary', 'number')},
            },
        ),
    ]
