# Generated by Django 4.2.28 on 2026-02-20 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catechism', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fishersubquestion',
            unique_together=set(),
        ),
    ]
