# Generated by Django 4.2.28 on 2026-02-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catechism', '0002_alter_fishersubquestion_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScripturePassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['reference'],
            },
        ),
    ]
