# Generated by Django 4.2.28 on 2026-02-20 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catechism', '0006_update_unique_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wlc_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wsc_cross_refs', to='catechism.question')),
                ('wsc_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wlc_cross_refs', to='catechism.question')),
            ],
            options={
                'ordering': ['wsc_question__number', 'wlc_question__number'],
                'unique_together': {('wsc_question', 'wlc_question')},
            },
        ),
    ]
