# Generated by Django 4.2.28 on 2026-02-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catechism', '0007_crossreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='catechism',
            name='document_type',
            field=models.CharField(choices=[('catechism', 'Catechism'), ('confession', 'Confession')], default='catechism', max_length=20),
        ),
    ]
