# Generated by Django 4.2.28 on 2026-02-21 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catechism', '0008_catechism_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('abbreviation', models.CharField(max_length=20)),
                ('book_number', models.PositiveIntegerField(unique=True)),
                ('testament', models.CharField(choices=[('OT', 'Old Testament'), ('NT', 'New Testament')], max_length=2)),
            ],
            options={
                'ordering': ['book_number'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StandardCrossReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_refs_from', to='catechism.question')),
                ('target_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_refs_to', to='catechism.question')),
            ],
            options={
                'ordering': ['source_question__catechism__abbreviation', 'source_question__number'],
                'unique_together': {('source_question', 'target_question')},
            },
        ),
        migrations.CreateModel(
            name='ScriptureIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_entries', to='catechism.biblebook')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripture_index_entries', to='catechism.question')),
            ],
            options={
                'ordering': ['book__book_number', 'question__catechism__abbreviation', 'question__number'],
                'unique_together': {('question', 'reference')},
            },
        ),
        migrations.CreateModel(
            name='ComparisonEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_start', models.PositiveIntegerField()),
                ('question_end', models.PositiveIntegerField()),
                ('catechism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_entries', to='catechism.catechism')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='catechism.comparisontheme')),
            ],
            options={
                'ordering': ['catechism__abbreviation'],
                'unique_together': {('theme', 'catechism')},
            },
        ),
    ]
