# Generated by Django 4.2.28 on 2026-02-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catechism', '0009_biblebook_comparisontheme_standardcrossreference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptureindex',
            name='reference',
            field=models.CharField(max_length=255),
        ),
    ]
