# Generated by Django 4.2.28 on 2026-02-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catechism', '0011_dataversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisontheme',
            name='locus',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dataversion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
