# Generated by Django 4.2.28 on 2026-02-22 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catechism', '0014_force_comparison_themes_reload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='comparisontheme',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='dataversion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='comparisontheme',
            name='comparison_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='catechism.comparisonset'),
        ),
        migrations.AlterUniqueTogether(
            name='comparisontheme',
            unique_together={('comparison_set', 'slug')},
        ),
    ]
