# Generated by Django 4.2.28 on 2026-02-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catechism', '0017_comparisontheme_comparison_set_non_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
