# Generated by Django 4.2.28 on 2026-02-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catechism", "0018_increase_topic_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catechism",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("catechism", "Catechism"),
                    ("confession", "Confession"),
                    ("systematic_theology", "Systematic Theology"),
                ],
                default="catechism",
                max_length=20,
            ),
        ),
    ]
