# Generated by Django 4.2.28 on 2026-06-11 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catechism', '0020_add_tradition_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='OntologyLocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=8)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('atlas_path', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OntologyAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=150)),
                ('baseline_label', models.CharField(blank=True, max_length=200)),
                ('baseline_slug', models.SlugField(blank=True)),
                ('baseline_description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('atlas_path', models.CharField(blank=True, max_length=255)),
                ('locus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catechism.ontologylocus')),
            ],
            options={
                'ordering': ['locus__order', 'order', 'name'],
                'unique_together': {('locus', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='DoctrineHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('atlas_path', models.CharField(blank=True, max_length=255)),
                ('locus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctrine_heads', to='catechism.ontologylocus')),
            ],
            options={
                'ordering': ['locus__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOntologyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_representative', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_tags', to='catechism.ontologyattribute')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ontology_tags', to='catechism.question')),
            ],
            options={
                'ordering': ['attribute__locus__order', 'attribute__order'],
                'unique_together': {('question', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='QuestionDoctrineHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctrine_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_links', to='catechism.doctrinehead')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctrine_head_links', to='catechism.question')),
            ],
            options={
                'ordering': ['doctrine_head__locus__order', 'doctrine_head__order'],
                'unique_together': {('question', 'doctrine_head')},
            },
        ),
    ]
