# Generated by Django 4.2.30 on 2026-08-23 17:17

from django.db import migrations, models

# The confessions that were loaded with the default tradition ('other') and so
# were unreachable on the site: every view gates on VALID_TRADITIONS, which did
# not include 'other'. Their comparison sets ("Confessional Lineage",
# "Pre-Westminster Confessions") were gated with them.
PUBLISHED_SLUGS = ["1689", "savoy", "scots", "second-helvetic", "irish"]


def publish_reformed_confessions(apps, schema_editor):
    Catechism = apps.get_model("catechism", "Catechism")
    Catechism.objects.filter(slug__in=PUBLISHED_SLUGS, tradition="other").update(
        tradition="reformed_confessions",
    )


def unpublish_reformed_confessions(apps, schema_editor):
    Catechism = apps.get_model("catechism", "Catechism")
    Catechism.objects.filter(
        slug__in=PUBLISHED_SLUGS, tradition="reformed_confessions",
    ).update(tradition="other")


class Migration(migrations.Migration):

    dependencies = [
        ("catechism", "0021_ontologylocus_ontologyattribute_doctrinehead_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catechism",
            name="tradition",
            field=models.CharField(
                choices=[
                    ("westminster", "Westminster Standards"),
                    ("three_forms_of_unity", "Three Forms of Unity"),
                    ("reformed_confessions", "Reformed Confessions"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.RunPython(
            publish_reformed_confessions, unpublish_reformed_confessions,
        ),
    ]
